config/routes.rb
Rails.application.routes.draw do
  get 'appointments/index'
  get 'appointments/new'
  root 'users#index'

  resources :users
  resources :physicians do
    resources :appointments, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :physician
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :physicians, through: :appointments

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_physician
  def index
    @appointments = @physician.appointments.order
  end

  def new
    @users = User.all - @physician.users
    @appointment = @physician.enrollments.new
  end

  def show
    @user = @appointment.user.find(params[:id])
    @physician = @appointment.physician.find(params[:physician_id])
  end

  def create
    @appointment = @physician.appointments.new(appointment_params)
    if @appointment.save
      redirect_to physician_appointments_path
    else
      render :new
    end
  end

  def destroy
    @physician.appointments.find(params[:id]).destroy
    redirect_to physician_appointments_path
  end


  private
    
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def set_doctor
      @physician = Physician.find(params[:physician_id])
    end

    def set_users
      @users = (User.all.order - @physician.users)
    end

    def appointment_params
      params.require(:appointment).permit(:patient_id)
    end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  def index
    @physicians = Physician.all
  end

  def show
  end

  def new
    @physician = Physician.new
  end

  def create 
    @physician = Physician.create(physician_params)

    if @physician.save
      redirect_to @physician
    else
      render :new
    end
  end

  def destroy
    @physician.destroy
    redirect_to physicians_path
  end

  private
    def set_physician
      @physician = Physician.find(params[:id])
    end

    def physician_params
      params.require(:physician).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :destroy]
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create 
  @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/index.html.erb
<h1>Appointments#index</h1>
<p>Find me in app/views/appointments/index.html.erb</p>

app/views/appointments/new.html.erb
<h1>Add Appointment</h1>
<%= form_with(model: [@physician, @appointment], local: true, class: "ui form" ) do |f| %>
  <%= f.label :user %>
  <%= f.select :user_id, @users.collect { |u| [u.full_name, u.id] } %>
  <br />
  <br />
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="navigation">
    <div class="nav-links">
      <%= link_to 'Doctors', physicians_path %>
      <%= link_to 'Add Doctors', new_physician_path %>
      <%= link_to 'Patients', users_path %>
      <%= link_to 'Add Patient', new_user_path %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doctor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
      <div class="ui container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/physicians/index.html.erb
<h1>Physicians</h1>
<%= link_to 'Add Physicians', new_physician_path %>
<br />
<ul>
  <% @physicians.each do |physician| %>
    <li>
      <%= link_to physician.name, physician%>
    </li>
  <% end %>
</ul>

app/views/physicians/new.html.erb
<h1>Add Physician</h1>
<%= form_with(model: @physician, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Physician Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/physicians/show.html.erb
<h1><%= @physician.name %></h1>
<hr />
<br />
<%= link_to 'Physicians', physician_appointments_path(@physician), class: "ui primary button inverted" %>
<br />
<br />
<br />
<%= link_to "Delete Physician", @physician, method: :delete, class: "ui red button inverted" %>

app/views/users/index.html.erb
<h1 class="header">Gotham City Hospital Appoitment Center</h1>
  <div class="boards">
  <% @users.each do |user| %>
    <%= link_to user.full_name, user_path(user), class:"user chart"%>
  <% end %>        
  </div>
</div>

app/views/users/new.html.erb
<h1>Add User</h1>
<%= form_with(model: @user, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  </div>
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<hr />
<h2>Doctors</h2>
<ul>
  <% @user.physicians.each do |physician| %>
    <li>
      <%= link_to physician.name, physician %>
    </li>
  <% end %>
</ul>
<br />
<br />
<br />
<%= link_to 'Delete User', @user, method: :delete, class: "ui red button inverted" %>